### ISSUE TITLE
API ERROR

### ISSUE THREAD

**Issue by charleslukes** [FlipsideCrypto/sdk#29]
Hello we started noticing this error all of a sudden from the sdk. 

Our sql query and API key still the same as before 

```js
QueryResultSetBuilder {
    error: ApiError: UnknownAPIError: message=, code=-1
        at getExceptionByErrorCode (/Users/charles/Desktop/pear-protocol/pear-backend/node_modules/@flipsidecrypto/sdk/src/errors/api-error.ts:37:12)
        at QueryIntegration.<anonymous> (/Users/charles/Desktop/pear-protocol/pear-backend/node_modules/@flipsidecrypto/sdk/src/integrations/query-integration/index.ts:62:39)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/charles/Desktop/pear-protocol/pear-backend/node_modules/@flipsidecrypto/sdk/dist/src/integrations/query-integration/index.js:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5),
    queryId: null,
    status: null,
    columns: null,
    columnTypes: null,
    rows: null,
    runStats: null,
    records: null,
    page: null
  }```
  
  We are not sure what could be the cause

**Comment by zkSoju** [comment]
hey did you end up finding a solution for this?
